from nvcr.io/nvidia/pytorch:22.02-py3

COPY artifact/setup/requirements.txt /opt/app/requirements.txt

WORKDIR /opt/app

RUN pip install -r requirements.txt 

# Packages that require runtime download can be cached by running the python -c "CODE"
# Replace "CODE" with the lines that handle downloading
# RUN python -c "CODE"

RUN python -c 'from transformers import T5Tokenizer,T5ForConditionalGeneration,HfArgumentParser,TrainingArguments,set_seed; T5Tokenizer.from_pretrained("t5-base"); T5ForConditionalGeneration.from_pretrained("t5-base")'

WORKDIR /workspace